error.name=Name is required
error.mobile=Mobile is required
error.email=Email is required

error.name.invalid=Invalid Name
error.mobile.invalid=Invalid Mobile Number
error.email.invalid=Invalid Email